variables:
  - &image "fin-kit-ci:latest"

steps:
  build-image:
    image: docker
    commands:
      - docker build -t fin-kit-ci:latest -f ci/Dockerfile .
    when:
      path:
        - "ci/Dockerfile"

  check-lockfile:
    image: *image
    commands:
      - uv sync --locked

  install-deps:
    image: *image
    commands:
      - uv sync
      - uv run conan profile detect --force
      - uv run conan install . --build=missing -of=build
    depends_on:
      - check-lockfile

  build-release:
    image: *image
    commands:
      - cmake --preset conan-release
      - cmake --build build --config Release
    depends_on:
      - install-deps

  test:
    image: *image
    commands:
      - ctest --test-dir build --output-on-failure
    depends_on:
      - build-release

  lint:
    image: *image
    commands:
      - uv sync
      - uv run pre-commit run --all-files
    depends_on:
      - check-lockfile

  build-debug:
    image: *image
    commands:
      - cmake --preset conan-debug
      - cmake --build build --config Debug
    depends_on:
      - install-deps
    when:
      branch: develop
